/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.dohado.car_sharing;

import com.dohado.carsharing.App;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
    }
}
