CREATE TABLE IF NOT EXISTS CAR(
	ID INTEGER AUTO_INCREMENT,
	NAME VARCHAR NOT NULL,
	COMPANY_ID INTEGER NOT NULL,
	CONSTRAINT pk_car_id PRIMARY KEY(ID),
	CONSTRAINT uq_car_name UNIQUE(NAME),
	CONSTRAINT fk_car_id_to_company_id FOREIGN KEY(COMPANY_ID) REFERENCES COMPANY(ID)
);