CREATE TABLE IF NOT EXISTS CUSTOMER(
ID INTEGER AUTO_INCREMENT,
NAME VARCHAR(128) NOT NULL,
RENTED_CAR_ID INT,
CONSTRAINT pk_cstmr_id PRIMARY KEY(ID),
CONSTRAINT uq_cstmr_name UNIQUE(NAME),
CONSTRAINT fk_cstm_rented_car_id_to_car_id FOREIGN KEY(RENTED_CAR_ID) REFERENCES CAR(ID)
);